variables:
    # Container registry service connection established during pipeline creation
    dockerRegistryServiceConnection: devops-acr-connection
    imageRepository: devops-course-repository
    containerRegistry: DevOpsLearn
    dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
    tag: 'latest'

    # Agent VM image name
    vmImageName: 'ubuntu-latest'

steps:

- task: AzureWebAppContainer@1 # Description what the task will execute
  inputs:
    azureSubscription: 'devops-appservice-resource-group'
    appName: 'devops-course-webapp-test-avi'
    containers: $(containerRegistry)/$(imageRepository):$(tag)